@server = https://organic-space-couscous-jxpjr7w467qcq9px-8080.app.github.dev
###
GET {{server}}/api/cursos/2
###
POST {{server}}/api/cursos
Content-Type: application/json

{"nombre": "Literatura", "categoria": "Letras", "descripcion": "Contenido de obras literarias"}
###
GET {{server}}/api/alumnos
###
POST {{server}}/api/alumnos
Content-Type: application/json

{"nombre": "Lucio"}
###
GET {{server}}/api/aulas
###
GET {{server}}/api/aulas/1
###
GET {{server}}/api/aulas/1/formacion
###
GET {{server}}/api/pabellones
